title: Josh Berger
description: Backend Software Engineer & Aspiring Game Developer
url: "https://joshberger5.github.io"
baseurl: ""

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
